spring:
  threads:
    virtual:
      enabled: true

providers:
  default:
    - url: https://www.kitgg4.com
      name: KitsGG
    - url: https://www.5boundless.com
      name: 5Boundless
    - url: https://www.grkits.com
      name: GRKits
    - url: https://www.aclotzone.co
      name: Aclotzone
    - url: https://www.fofoshop3.com
      name: Fofoshop
    - url: https://www.kotofanss.com
      name: Kotofanss
    - url: https://www.kegaoo.cn
      name: Kegaoo
    - url: https://www.jjsport01.com
      name: JJSport
    - url: https://www.fcstore24.com
      name: FCstore24
    - url: https://www.jeofc1.com
      name: JeoFc1
    - url: https://www.gkkoc.com
      name: GKKOC
    - url: https://www.soccer03.com
      name: Soccer

fetchers:
  default-timeout: 3s
