spring:
  threads:
    virtual:
      enabled: true

providers:
  list-r-1:
    - url: https://www.kitgg4.com
      name: KitsGG
    - url: https://www.5boundless.com
      name: 5Boundless
## GRKits is blocking us
##    - url: https://www.grkits.com
##      name: GRKits
    - url: https://www.aclotzone.co
      name: Aclotzone
    - url: https://www.fofoshop3.com
      name: Fofoshop
    - url: https://www.kotofanss.com
      name: Kotofanss
    - url: https://www.kegaoo.cn
      name: Kegaoo
    - url: https://www.jjsport01.com
      name: JJSport
    - url: https://www.fcstore24.com
      name: FCstore24
    - url: https://www.jeofc1.com
      name: JeoFc1
    - url: https://www.gkkoc.com
      name: GKKOC
    - url: https://www.soccer03.com
      name: Soccer
    - url: https://www.messi105.com
      name: Messi100
    - url: https://www.mmjerseys00.com
      name: MMJerseys00
    - url: https://www.lindajersey.com
      name: LindaJersey
    - url: https://www.halosport.cn
      name: HaloSport
    - url: https://www.motios1.com
      name: Motios1
    - url: https://www.vicksports.com
      name: VickSports
    - url: https://www.jshop1.com
      name: JShop
    - url: https://www.bqlsport.com
      name: BQL Sports

fetchers:
  default-timeout: 3s
