spring:
  threads:
    virtual:
      enabled: true

providers:
  default-timeout: 3s
  kitsgg:
    url: https://www.kitgg4.com
    metadata:
      name: KitsGG
  five-boundless:
    url: https://www.5boundless.com
    metadata:
      name: 5Boundless
  grkits:
    url: https://www.grkits.com
    metadata:
      name: GRKits
  aclotzone:
    url: https://www.aclotzone.co
    metadata:
      name: Aclotzone
  fofoshop:
    url: https://www.fofoshop3.com
    metadata:
      name: Fofoshop
  kotofanss:
    url: https://www.kotofanss.com
    metadata:
      name: Kotofanss
  kegaoo:
    url: https://www.kegaoo.cn
    metadata:
      name: Kegaoo
  jjsport:
    url: https://www.jjsport01.com
    metadata:
      name: JJSport
  fcstore24:
    url: https://www.fcstore24.com
    metadata:
      name: FCstore24
  jeofc1:
    url: https://www.jeofc1.com
    metadata:
      name: JeoFc1
  gkkoc:
    url: https://www.gkkoc.com
    metadata:
      name: GKKOC
  soccer:
    url: https://www.soccer03.com
    metadata:
      name: Soccer
