on:
  schedule:
    - 0 0 * * *
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        uses: juancolchete/batch-http-request
        with:
          url: 'https://api.shirtscanner.com/v1/providers'
