on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.shirtscanner.com/v1/providers'
