on:
  push:
    branches:
      - main

name: Build and Test code
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to Docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth docker

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Test
        run: |
          ./gradlew build

      - name: Build Docker Image
        run: |
          ./gradlew bootBuildImage --imageName registry.fly.io/shirtscanner-be:${{ steps.version.outputs.version }}

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy -i registry.fly.io/shirtscanner-be:${{ steps.version.outputs.version }}

      - name: Tag Version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}